import glob
import json
import logging
import os
import time
from pathlib import Path
from pprint import pformat

import boto3
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util import AutogenerateDiffsDetected
from pymysql.err import OperationalError
from sqlalchemy import create_engine, text
from sqlalchemy.engine.url import URL
from sqlalchemy.pool import NullPool

logger = logging.getLogger()
logger.setLevel(logging.INFO)

def get_secrets(secret_name):
    """
    Retrieve AWS Secrets Manager credentials as a dictionary.

    This function queries AWS Secrets Manager for the specified secret and
    returns the parsed JSON content. It is intended to run only within the
    RDMT AWS environment.

    Parameters
    ----------
    secret_name : str
        The name or ARN of the secret stored in AWS Secrets Manager.

    Returns
    -------
    dict
        A dictionary containing the secret values retrieved from AWS Secrets
        Manager. The structure of the returned dictionary depends on the
        contents of the stored secret.
    
    """
    region_name = "us-east-1"

    # Create a Secrets Manager client
    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )

    try:
        get_secret_value_response = client.get_secret_value(
            SecretId=secret_name
        )
    except Exception as e:
        # For a list of exceptions thrown, see
        # https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
        raise e
    database_secrets = json.loads(get_secret_value_response['SecretString'])

    return database_secrets

def get_connection_url(secret_name, db_name=None):
    """
    Construct a MySQL database connection URL using retrieved secrets.

    Retrieves credentials and connection details from ``get_secrets(secret_name)`` and
    assembles a SQLAlchemy-compatible MySQL connection URL. If a database
    name is provided, it is appended to the URL; otherwise, only the base
    server URL is returned.

    Parameters
    ----------
    secret_name : str
        The name of the secret in AWS Secrets Manager containing the database
        credentials and connection details.
    db_name : str or None, optional
        The database name to append to the connection URL. If ``None``
        (default), the returned URL will not include a database segment.

    Returns
    -------
    URL
        A fully constructed SQLAlchemy MySQL connection URL, with or without a
        database name appended.

    """
    secret = get_secrets(secret_name)
    return URL.create(
        drivername="mysql+pymysql",
        username=secret['username'],
        password=secret['password'],
        host=secret['host'],
        database=db_name,
    )

def get_engine_from_url(connection_url, recursive_depth=0):
    """
    Create a SQLAlchemy engine from a database connection URL.

    This function attempts to construct a SQLAlchemy engine using the provided
    connection URL. The engine is created with a ``NullPool`` to avoid connection
    reuse across invocations, which can be useful in serverless or short-lived
    execution environments. If engine creation fails, the exception is logged
    and re-raised.

    Parameters
    ----------
    connection_url : str
        A SQLAlchemy-compatible database connection URL. Examples include
        PostgreSQL, MySQL, and other supported dialect URLs.

    Returns
    -------
    sqlalchemy.engine.Engine
        A SQLAlchemy engine instance configured with ``NullPool``.

    """
    # create the server/database connection outside of the handler to allow connections to be
    # re-used by subsequent function invocations.
    try:
        engine = create_engine(connection_url, poolclass=NullPool)
    except Exception as e:
        logger.error(f"ERROR: Unexpected error: Could not create SQLAlchemy engine for {str(connection_url).split('@')[-1]}.")
        logger.error(e)
        raise e # TODO: think about how to possibly handle this error better. Do we want to run Spire if no DB is available?
    
    try:
        connection = engine.connect()
    except OperationalError as e:
        if e.args[0] == 2003: # database connection timeout error
            wait_time = 5
            max_retries = 2
            logger.warning(f"Received database timeout error. Waiting {wait_time} seconds and retrying.")
            time.sleep(wait_time) # wait for the database to wake up
            if recursive_depth < max_retries: # only repeat the process a set number of times
                engine = get_engine_from_url(connection_url, recursive_depth=recursive_depth+1)
            else:
                logger.error(f'Retried to connect to the database {max_retries} times and still failed.')
                raise e
        else:
            raise e
    finally:
        if 'connection' in locals() and (not connection.closed):
            connection.close()

    
    logger.info(f"SUCCESS: Connected to {str(connection_url).split('@')[-1]} using SQLAlchemy.")
    return engine

def connect_to_db(database_name, secret_name):
    """
    Create and return an SQLAlchemy engine for the specified database.

    This function connects to the database server using helper utilities,
    verifies that the target database exists (creating it if necessary), and
    then returns an SQLAlchemy Engine object connected to that database.

    Parameters
    ----------
    database_name : str or None
        Name of the database to connect to. If the database does not exist,
        it will be created automatically.
    secret_name : str
        The name of the secret in AWS Secrets Manager containing the database
        credentials and connection details.

    Returns
    -------
    engine : sqlalchemy.engine.Engine
        An SQLAlchemy engine connected to the specified database.

    """
    # try to connect to the database
    database_string = get_connection_url(secret_name=secret_name, db_name=database_name)

    try:
        database_engine = get_engine_from_url(database_string)
    except Exception:
        logger.info(f"Connection to {database_name} failed. Checking if database exists.")
        # try to connect to the server and see if database exists
        server_string = get_connection_url(secret_name=secret_name)
        server_engine = get_engine_from_url(server_string)

        # ensure the desired database exists
        with server_engine.connect() as connection:
            result = connection.execute(text(f"SHOW DATABASES LIKE '{database_name}';"))
            results_as_dict = result.mappings().all()
            if len(results_as_dict) == 0:
                logger.warning(f"Database '{database_name}' does not exist. Creating database.")
                connection.execute(text(f"CREATE DATABASE {database_name}"))
                connection.commit() 
        logger.info(f"Database '{database_name}' exists.")

        # clean up the server engine 
        server_engine.dispose()

        # reconnect to the database
        database_engine = get_engine_from_url(database_string)
    
    return database_engine


def download_migration_scripts_from_s3(s3_bucket, alembic_file_local_path, s3_client=None):
    """
    Downloads migration scripts from S3 to a local directory.
    
    Parameters
    ----------
    s3_bucket : str
        Name of the S3 bucket where the version scripts are stored.
    alembic_file_local_path : str or pathlib.Path
        Local path where the version scripts will be stored.
    s3_client : boto3.s3.client (default = None)
        AWS SDK S3 client object

    """
    if s3_client is None:
        s3_client = boto3.client('s3')

    if isinstance(alembic_file_local_path, str):
        alembic_file_local_path = Path(alembic_file_local_path)
    alembic_version_local_path = alembic_file_local_path / "versions"
    alembic_version_local_path.mkdir(parents=True, exist_ok=True)
    
    # remove any existing version .py files
    pattern = str(alembic_version_local_path / "*.py")
    
    # Use glob to get a list of all matching .py files
    py_files = glob.glob(pattern)
    
    if py_files:
        logger.info(f"Found .py files in '{alembic_version_local_path}':")
        for file_path in py_files:
            try:
                os.remove(file_path)
                logger.info(f"  Deleted: {file_path}")
            except OSError as e:
                logger.info(f"  Error deleting {file_path}: {e}")

    response = s3_client.list_objects_v2(Bucket=s3_bucket)
    if 'Contents' in response:
        for obj in response['Contents']:
            key = obj['Key']
            local_file_path = alembic_version_local_path / key
            s3_client.download_file(s3_bucket, key, local_file_path)
            logger.info(f"Downloaded: {key} to {local_file_path}")

def run_alembic_upgrade(
    alembic_ini_path: str,
    script_location: str,
    revision_str: str,
    allow_update=False,
    save_revision=False,
    app_logger=None,
    skip_alembic_file_config=True,
) -> None:
    """
    Runs the 'alembic upgrade revision_str' command programmatically.

    Parameters
    ----------
    alembic_ini_path : str
        Path to the alembic.ini configuration file.
    script_location : str
        Path to the Alembic migration script directory.
    revision_str : str
        SHA string unique to the revision to upgrade to.
    allow_update : bool (default = False)
        Trigger to allow database to update. True allows updates to be made, false prevents updates but highlights what changes would be made.

    Returns
    -------
    db_update_needed : bool
        True when the database checking process indicates a change needs to be made. False when the database is already up-to-date.
    revision path : str or None
        Local path to the version.py file created by the upgrade. None if no new file was created.

    """
    # Create an Alembic Config object
    logger.info("Setting up alembic config")
    alembic_cfg = Config(alembic_ini_path)
    if app_logger is not None:
        alembic_cfg.attributes["app_logger"] = app_logger
    alembic_cfg.attributes["skip_alembic_file_config"] = skip_alembic_file_config

    # Set the script_location if provided, otherwise it will use the one in alembic.ini
    alembic_cfg.set_main_option("script_location", script_location)

    # if trying to upgrade to latest revision, check if database is already up to date
    if revision_str == "head":
        try:
            logger.info("Running 'alembic check' to detect schema deviations...")
            command.check(alembic_cfg)
            logger.info("Alembic check passed: No new migrations needed.")
            db_update_needed = False
        except AutogenerateDiffsDetected as e:
            # This specific exception is usually raised when the check fails
            logger.warning(f"alembic detected differences:\n{pformat(e.diffs, width=60)}")
            logger.warning("New migrations are needed.")
            db_update_needed = True
    else:
        db_update_needed = True

    if db_update_needed:
        rev = None
        if revision_str == "head":
            try:
                logger.warning('Running alembic revision with auto-generation.')
                rev = command.revision(alembic_cfg, autogenerate=True)
                logger.info('Alembic revision successfully generated.')
            except Exception as e:
                logger.error(f"Error running Alembic revision: {e}")

        if allow_update:
            # Run the upgrade command to the 'head' revision
            try:
                logger.info(f"Running Alembic upgrade to '{revision_str}'.")
                command.upgrade(alembic_cfg, revision_str)
                logger.info(f"Alembic upgrade to '{revision_str}' completed successfully.")
            except Exception as e:
                logger.error(f"Error running Alembic upgrade: {e}")

            if rev is None:
                return db_update_needed, None
            else:
                return db_update_needed, rev.path
        else:
            logger.info("Skipping upgrade as allow_update = False.")

        if save_revision:
            return db_update_needed, rev.path
        else:
            return db_update_needed, None
    else:
        return db_update_needed, None

def run_alembic_downgrade(
    alembic_ini_path: str,
    script_location: str,
    revision_str: str,
    allow_update=False,
    app_logger=None,
    skip_alembic_file_config=True,
) -> None:
    """
    Runs the 'alembic downgrade revision_str' command programmatically.

    Parameters
    ----------
    alembic_ini_path : str
        Path to the alembic.ini configuration file.
    script_location: 
        Path to the Alembic migration script directory.
    revision_str : str
        SHA string unique to the revision to downgrade to.
    allow_update : bool (default = False)
        Trigger to allow database to update. True allows updates to be made, false prevents updates but highlights what changes would be made.

    Returns
    -------
    versions_to_delete : list of str or None
        Local path(s) to the version.py file(s) reverted by the downgrade. None if no downgrade occurred.

    """
    # Create an Alembic Config object
    logger.info("Setting up alembic config")
    alembic_cfg = Config(alembic_ini_path)
    if app_logger is not None:
        alembic_cfg.attributes["app_logger"] = app_logger
    alembic_cfg.attributes["skip_alembic_file_config"] = skip_alembic_file_config

    # Set the script_location if provided, otherwise it will use the one in alembic.ini
    alembic_cfg.set_main_option("script_location", script_location)

    logger.info(f"Checking for revisions above '{revision_str}'.")
    script = ScriptDirectory.from_config(alembic_cfg)
    revs = list(script.iterate_revisions(lower=revision_str, upper="head"))
    for rev in revs:
        logger.info(f"Found revision '{rev}' ('{rev.path}') to remove during downgrade.")

    versions_to_delete = None
    if allow_update:
        # Run the upgrade command to the 'head' revision
        try:
            logger.info(f"Running Alembic downgrade to '{revision_str}'.")
            command.downgrade(alembic_cfg, revision_str)
            logger.info(f"Alembic downgrade to '{revision_str}' completed successfully.")
            versions_to_delete = revs
        except Exception as e:
            logger.error(f"Error running Alembic downgrade: {e}")

    else:
        logger.info("Skipping downgrade as allow_update = False.")
    
    return versions_to_delete