# thresholds for evaluating the metrics
PLATE_SCALE_CENTER_X_THRESHOLD = 1
PLATE_SCALE_CENTER_Y_THRESHOLD = 1

DELTA_PLATE_SCALE_CORNER_BL_THRESHOLD = 1
DELTA_PLATE_SCALE_CORNER_BR_THRESHOLD = 1
DELTA_PLATE_SCALE_CORNER_TL_THRESHOLD = 1
DELTA_PLATE_SCALE_CORNER_TR_THRESHOLD = 1
DELTA_PLATE_SCALE_CENTER_THRESHOLD = 1
PLATE_SCALE_THRESHOLDS = {
            "PLATE_SCALE_CENTER_X": PLATE_SCALE_CENTER_X_THRESHOLD,
            "PLATE_SCALE_CENTER_Y": PLATE_SCALE_CENTER_Y_THRESHOLD,
            "DELTA_PLATE_SCALE_CORNER_BL": DELTA_PLATE_SCALE_CORNER_BL_THRESHOLD,
            "DELTA_PLATE_SCALE_CORNER_BR": DELTA_PLATE_SCALE_CORNER_BR_THRESHOLD,
            "DELTA_PLATE_SCALE_CORNER_TL": DELTA_PLATE_SCALE_CORNER_TL_THRESHOLD,
            "DELTA_PLATE_SCALE_CORNER_TR": DELTA_PLATE_SCALE_CORNER_TR_THRESHOLD,
            "DELTA_PLATE_SCALE_CENTER": DELTA_PLATE_SCALE_CENTER_THRESHOLD,
        }
# Since we're only evaluating a subset of the metrics,
# I'm making a list of the names to easily iterate
# TODO: should there be a helper method in the base class to get datacard names? 
DETECTOR_AREAS = [
    "CORNER_BL",
    "CORNER_BR",
    "CORNER_TL",
    "CORNER_TR",
    "CENTER",
]

PIXEL_STATISTICS_METRIC_NAMES = [
    f"PLATE_SCALE_{da}_X" for da in DETECTOR_AREAS
] + [
    f"PLATE_SCALE_{da}_Y" for da in DETECTOR_AREAS
] + [
    f"DELTA_PLATE_SCALE_{da}" for da in DETECTOR_AREAS
] + ['N_SATURATED_PIX',
     'MIN_RAMP_VALUE',
     'MAX_RAMP_VALUE',
     'MEAN_RAMP_VALUE',
     'MEDIAN_RAMP_VALUE',
     'STD_RAMP_VALUE',
     'P95_RAMP_VALUE',
     'P05_RAMP_VALUE'
]